name: CI
on:
  push:
    branches:
      - master
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.4', '8.6', '8.8', '8.10', '9.0']
        include:
        - os: windows-latest
          ghc: 'latest'
        - os: macOS-latest
          ghc: 'latest'
    steps:
    - uses: actions/checkout@v4
    - uses: haskell/actions/setup@v2.4.7
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - name: Install hspec-discover
      run: cabal install hspec-discover
    - uses: actions/cache@v4.0.1
      name: Cache cabal output
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Test
      run: |
        cabal sdist -z -o .
        cabal get isbn-*.tar.gz
        cd isbn-*/
        cabal test --test-show-details=direct
    - name: Haddock
      run: cabal haddock

#   build-freebsd:
#     # The FreeBSD environment uses MacOS for its virtualization
#     # See: https://github.com/vmactions/freebsd-vm#under-the-hood.
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Test
#       id: build-freebsd
#       uses: vmactions/freebsd-vm@v0.1.5
#       with:
#         usesh: true
#         mem: 4096
#         prepare: pkg install -y ghc hs-cabal-install git
#         # Virtual machine does not allow to leverage cache
#         # and is quite slow, so only tests are run.
#         run: |
#           cabal update
#           cabal install hspec-discover
#           cabal test --test-show-details=direct
